### ISSUE TITLE
Spike (extra): repeticion de codigo entre subclases de TreeNode

### ISSUE THREAD

**Issue by FScaccheri** [dylanalvarez/tp1-sistemas-graficos#36]
- En la creacion de cualquier objeto que sea subclase de `TreeNode` se llama siempre al constructor del mismo, dicho constructor llama al metodo `buildBuffers`, que siempre invoca al metodo definido en la clase hija que se esta instanciando.
- Ejemplo: Se instancia una `Sphere`, lo cual hace un llamado al constructor de `TreeNode`, el cual hace un llamado al `buildBuffers` de `Sphere`
- Problema: dependiendo del objeto hijo que se esta instanciando, `buildBuffers` necesita ciertos parametros que otros hijos pueden o no tener. No alcanza con definir estos parametros en el constructor y se opto por repetir el codigo de `buildBuffers` en cada hijo, agregando los parametros que cada uno requiera.
- Solucion propuesta: que el constructor de `TreeNode` acepte dichos atributos como parametros opcionales (es decir, atributos que toman el valor de cada parametro, si se les pasa, un valor default en caso contrario)

Como `buildBuffers` es un metodo que cada hijo _debe_ definir y el unico problema potencial que esto conlleva es la repeticion de codigo **es muy probable que este sea un non issue**

**Comment by dylanalvarez** [comment]
Se trabajará en [TP2](https://github.com/dylanalvarez/tp2-sistemas-graficos)
